services:
# {% for index in range(REDROID_COUNT) %}
# {% with name = 'redroid' + (REDROID_ADB_PORT + index * 2 - 1)|string %}
  {{ name }}:
    image: {{ REDROID_IMAGE }}
    network_mode: bridge
    privileged: true
    volumes:
      - '{{ mkdir(APP_PATH/"data"/name) | chown }}:/data'
      - '/dev/mali0:/dev/mali0'
      - '/dev/net/tun:/dev/tun'
#     {% for key, value in container.overlay_files.items() %}
      - '{{ key }}:{{ value }}'
#     {% endfor %}
    ports:
      - '{{ REDROID_ADB_PORT + index * 2 }}:5555'
    command:
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=1920
      - androidboot.redroid_dpi=480
      - androidboot.redroid_gpu_mode={{ REDROID_GPU_MODE }}
      - androidboot.redroid_virtual_wifi={{ 1 if REDROID_VIRTUAL_WIFI else 0 }}
# {% endwith %}
# {% endfor %}
