services:
  redroid_builder:
    user: '{{ DOCKER_PUID }}:{{ DOCKER_PGID }}'
    volumes:
      - '{{ container.get_build_path() }}:/src'
      - '{{ container.get_path("scripts") }}:/usr/local/bin/scripts:ro'
    environment:
      - 'LANG=en_US.UTF-8'
#     {% for key, value in container.get_envvars().items() %}
      - '{{ key }}={{ value }}'
#     {% endfor %}
    working_dir: "/src"
    networks:
      - build

networks:
  build:
    name: build
