services:
  redroid_builder:
    user: '{{ DOCKER_PUID }}:{{ DOCKER_PGID }}'
    volumes:
      - '{{ REDROID_BUILD_PATH }}:/src'
    working_dir: "/src"
    networks:
      - build

networks:
  build:
    name: build
